services:
  llmserver:
    image: ollama/ollama:rocm
    container_name: llmdevosku-llmserver
    volumes:
      - ./data:/root/.ollama
    restart: always

    devices: 
      - /dev/kfd
      - /dev/dri
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/health || exit 1"]

    # command:
    #   - --verbose

  reverse-proxy:
    image: nginx:latest
    container_name: llmdevosku-reverse-proxy
    ports:
      - "8020:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - llmserver

